name: angulardart_app
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: kevinalexandersurjadi <email@example.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  sass_builder: ^2.1.2
  core_app:
    path: ../core_app
  async_resource:
    git:
      url: git@gitlab.com:ovaltech/async_resource.git
      ref: v0.2.1

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
